### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by TheBrokenRail** [Snakefangox/FasterThanC#2]
- Add A Fire All Button To the Targeting Computer
- The Basic Laser name isn't translated in the Targeting Computer for some reason

**Comment by snakefangox** [comment]
Yeah, I've accidentally hit an integrated vs dedicated server different with that translation. It shouldn't be a tough fix, I'll work it out. 

A fire all button is a good idea, just got to figure out where to add it to the UI.

**Comment by TheBrokenRail** [comment]
Solved by #6
